repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: detect-private-key
  - id: name-tests-test
    args: ['--django']
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.2.0
  hooks:
  - id: reorder-python-imports
    args: ['--py3-plus']
- repo: https://github.com/psf/black
  rev: '19.10b0'
  hooks:
  - id: black
    language_version: python3.7
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
